### ISSUE TITLE
https://demo-cross.piral.io/ doesn't work

### ISSUE THREAD

**Issue by larsw** [smapiot/sample-cross-fx-pilets#2]
![image](https://github.com/smapiot/sample-cross-fx-pilets/assets/63235/1a9a9c8e-4072-4383-a65d-66817aae56e3)

:-/

**Comment by FlorianRappl** [comment]
I know - it will be fixed with 1.4.0; sorry for the inconvenience (you can also build / run from the `develop` branch already).

This is an unfortunate problem with zone.js in combination with the used WC package.

**Comment by larsw** [comment]
Ok, thanks for the quick response!

**Comment by FlorianRappl** [comment]
Sure, sorry that it broke. I realized it like one or two weeks ago, but I did not want to release a fix just for this page to work again. Maybe I hotfix this without doing a full release; depends on how far we get with the 1.4.0 in the next couple of days.
